version: '3.1'

services:

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: wallbase
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallbase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - common

  wallbase:
    image: lexkrstn/wallbase
    restart: always
    command: >
      sh -c "npm run knex migrate:latest &&
             npm run knex seed:run &&
             npm start"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:qwerty@postgres:5432/wallbase
      DATABASE_SSL: 0
      SSL: 0
      PORT: 3000
    networks:
      - common
    logging:
      driver: json-file
      options:
        max-size: 50K
        max-file: "10"

networks:
  common:
    driver: bridge

volumes:
  pgdata:
