version: '3.1'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wallbase
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallbase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres

  wallbase:
    image: lexkrstn/wallbase
    restart: always
    depends_on:
      - postgres
    ports:
      - "443:443"
      - "3000:3000"
    volumes:
      - /opt/wallbase/tls:/opt/wallbase/tls
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:qwerty@localhost:5432/wallbase
      SSL: 1
      PORT: 443
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
