const Purity = {
  SFW: 1,
  SKETCHY: 2,
  NSFW: 4,
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  await knex('tags').insert([
    {
      name: 'abstract',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'nature',
      creator_id: 1,
      category_id: 97,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'artwork',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'landscapes',
      creator_id: 1,
      category_id: 70,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'animals',
      creator_id: 1,
      category_id: 74,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'minimalistic',
      creator_id: 1,
      category_id: 96,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'trees',
      creator_id: 1,
      category_id: 97,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'anime',
      creator_id: 1,
      category_id: 2,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'actress',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'flowers',
      creator_id: 1,
      category_id: 97,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'cities',
      creator_id: 1,
      category_id: 90,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'Star Wars',
      creator_id: 1,
      category_id: 80,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'mountains',
      creator_id: 1,
      category_id: 70,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'cats',
      creator_id: 1,
      category_id: 74,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'typography',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'outdoors',
      creator_id: 1,
      category_id: 89,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'vehicles',
      creator_id: 1,
      category_id: 69,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'forest',
      creator_id: 1,
      category_id: 97,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'music',
      creator_id: 1,
      category_id: 81,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'multicolor',
      creator_id: 1,
      category_id: 95,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'beach',
      creator_id: 1,
      category_id: 89,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'text',
      creator_id: 1,
      category_id: 88,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'blue',
      creator_id: 1,
      category_id: 95,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'black',
      creator_id: 1,
      category_id: 95,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'fantasy art',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'funny',
      creator_id: 1,
      category_id: 79,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'faces',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'water',
      creator_id: 1,
      category_id: 5,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'celebrity',
      creator_id: 1,
      category_id: 72,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'portrait',
      creator_id: 1,
      category_id: 103,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'short hair',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'lingerie',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: '',
    },
    {
      name: 'long hair',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'arched back',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'thongs',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: '',
    },
    {
      name: 'thighs',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SKETCHY,
      alias: '',
    },
    {
      name: 'ass',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SKETCHY,
      alias: 'asses, bum, butt, butts, buttocks',
    },
    {
      name: 'anime girls',
      creator_id: 1,
      category_id: 2,
      purity: Purity.SFW,
      alias: 'manga girls',
    },
    {
      name: 'back',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SFW,
      alias: 'backs',
    },
    {
      name: 'bent over',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SKETCHY,
      alias: 'ass up, ass up face down, bend over, butt up, doggy, doggy style, doggystyle, face down, face down ass up, on all fours, on hands and knees',
    },
    {
      name: 'blonde',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'blonde hair, blondes',
    },
    {
      name: 'knee-highs',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SFW,
      alias: 'high socks, knee-high socks, knee highs, kneehighs, knee high socks, kneehigh socks, knee socks, kneesocks',
    },
    {
      name: 'dyed hair',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SFW,
      alias: 'hair dye',
    },
    {
      name: 'panties',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: 'pantsu, panty',
    },
    {
      name: 'panties down',
      creator_id: 1,
      category_id: 83,
      purity: Purity.NSFW,
      alias: 'pulling down panties',
    },
    {
      name: 'removing panties',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: 'undressing',
    },
    {
      name: 'shaved vagina',
      creator_id: 1,
      category_id: 73,
      purity: Purity.NSFW,
      alias: 'shaved pussies, shaved pussy, shaved vaginas',
    },
    {
      name: 'sideboob',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SKETCHY,
      alias: 'side boob, sideboobs, side boobs',
    },
    {
      name: 'smiling',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'smile, smiles',
    },
    {
      name: 'striped panties',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: 'shimapan, striped underwear',
    },
    {
      name: 'tatoo',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'tattooed, tattoos',
    },
    {
      name: 'shoes',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'women',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'babes, woman, female, girls, lady',
    },
    {
      name: 'nude',
      creator_id: 1,
      category_id: 1,
      purity: Purity.NSFW,
      alias: 'naked, nudes',
    },
    {
      name: 'asian',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'asians',
    },
    {
      name: 'curve women',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SKETCHY,
      alias: 'curvaceous, curves, curvy bodies, curvy body, feminine bodies, juicy, juicy women, sexy bodies, sexy body, voluptuous',
    },
    {
      name: 'boobs',
      creator_id: 1,
      category_id: 73,
      purity: Purity.NSFW,
      alias: 'boob, boobies, breast, breasts, tits, titties, titts',
    },
    {
      name: 'nipples',
      creator_id: 1,
      category_id: 73,
      purity: Purity.NSFW,
      alias: 'nippels, nipple',
    },
    {
      name: 'bathtubs',
      creator_id: 1,
      category_id: 96,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'strategic covering',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SKETCHY,
      alias: '',
    },
    {
      name: 'in bed',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SKETCHY,
      alias: 'lying in bed, lying on bed',
    },
    {
      name: 'small boobs',
      creator_id: 1,
      category_id: 73,
      purity: Purity.NSFW,
      alias: 'flat chest, flat chested, pettanko, small breasts',
    },
    {
      name: 'rock',
      creator_id: 1,
      category_id: 5,
      purity: Purity.SFW,
      alias: 'rocks, rocky',
    },
    {
      name: 'looking down',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'river',
      creator_id: 1,
      category_id: 70,
      purity: Purity.SFW,
      alias: 'rivers, stream, streams',
    },
    {
      name: 'bra',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: 'bras, brassiere',
    },
    {
      name: 'bikini',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SKETCHY,
      alias: 'bikini bottom, bikinis',
    },
    {
      name: 'wet body',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SKETCHY,
      alias: 'wet ass, wet asses, wet belly, wet bodies, wet boob, wet boobs, wet breast, wet breasts, wet chest, wet pussies, wet pussy, wet stomach, wet vaginas',
    },
    {
      name: 'flat belly',
      creator_id: 1,
      category_id: 73,
      purity: Purity.SKETCHY,
      alias: 'flat bellies, flat stomach, flat stomachs, flat tummies, flat tummy',
    },
    {
      name: 'car',
      creator_id: 1,
      category_id: 99,
      purity: Purity.SFW,
      alias: 'cars',
    },
    {
      name: 'women with glasses',
      creator_id: 1,
      category_id: 1,
      purity: Purity.SFW,
      alias: 'girls with glasses, girl with glasses, woman with glasses',
    },
    {
      name: 'glasses',
      creator_id: 1,
      category_id: 83,
      purity: Purity.SFW,
      alias: '',
    },
    {
      name: 'digital art',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: 'Cgi, digital artwork, digital compositions, graphic, graphics',
    },
    {
      name: 'video games',
      creator_id: 1,
      category_id: 78,
      purity: Purity.SFW,
      alias: 'game, game art, games, gaming, video game, videogame, videogames, video games art',
    },
    {
      name: 'pixel art',
      creator_id: 1,
      category_id: 75,
      purity: Purity.SFW,
      alias: 'bit art, pixel, pixelart, pixelated',
    },
  ]);
};
